### PR TITLE
Fix #99

### LINKED ISSUE #99: On hover darken nav bar button
This will make it easier for people to see the difference between the button the user is trying to press and the normal button.

### PR DESCRIPTION
**Pull request by GreenBayRules**
Fixes #99, the color I used for hovering is "#2793c5" Also, I made it so there is no underline on the navbar links.

### CODE REVIEW

**Comment by RedMAngo22** [comment]
Nice

**Comment by GreenBayRules** [comment]
Hmm... It doesn't say what failed. It just says this:
`- ./src/components/navbar/navbar.scss
    at Function.sassLint.failOnError (/home/travis/build/LLK/scratchjr-website/node_modules/sass-lint/index.js:313:11)
    at detectPattern (/home/travis/build/LLK/scratchjr-website/node_modules/sass-lint/bin/sass-lint.js:31:10)
    at /home/travis/build/LLK/scratchjr-website/node_modules/sass-lint/bin/sass-lint.js:83:5
    at Array.forEach (native)
    at Object.<anonymous> (/home/travis/build/LLK/scratchjr-website/node_modules/sass-lint/bin/sass-lint.js:82:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
make[1]: *** [lint] Error 1
make[1]: Leaving directory `/home/travis/build/LLK/scratchjr-website'
make: *** [test] Error 2
npm ERR! Test failed.  See above for more details.`

**Comment by thisandagain** [comment]
If you look at the test output it says:
```
32:23  error    Color literals such as '#2793c5' should only be used in variable declarations  no-color-literals
```

**Comment by GreenBayRules** [comment]
Oh okay, thanks @thisandagain I'll try to fix that :D

**Comment by GreenBayRules** [comment]
Yay :D The travis build passed!

**Pull request merged**
